# Generated by Django 5.2.3 on 2025-07-04 13:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Facilityadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('WEEK_BEFORE', 'One Week Before'), ('TWO_DAYS_BEFORE', 'Two Days Before'), ('MISSED_APPOINTMENT', 'Missed Appointment')], max_length=20)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordID', models.CharField(max_length=20, unique=True)),
                ('administrationDate', models.DateTimeField(auto_now_add=True)),
                ('doseNumber', models.IntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-administrationDate'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('birth_height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facilityadmin.healthcarew')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curve_type', models.CharField(choices=[('WEIGHT_AGE', 'Weight for Age'), ('HEIGHT_AGE', 'Height for Age'), ('WEIGHT_HEIGHT', 'Weight for Height')], max_length=20)),
                ('percentile', models.DecimalField(decimal_places=2, help_text="Child's percentile (0-100)", max_digits=5)),
                ('z_score', models.DecimalField(decimal_places=2, help_text='Standard deviation from mean', max_digits=5)),
                ('date_calculated', models.DateField()),
                ('is_normal_range', models.BooleanField(default=True)),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_curves', to='HealthcareW.child')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='HealthcareW.child')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facilityadmin.healthcarew')),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'National ID must contain only numbers')])),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('temporary_password', models.CharField(max_length=128)),
                ('password_changed', models.BooleanField(default=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facilityadmin.healthcarew')),
            ],
        ),
    ]
