# Generated by Django 5.2.3 on 2025-07-04 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthcareW', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='HealthcareW.guardian'),
        ),
    ]
