# Generated by Django 5.2.3 on 2025-07-07 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facilityadmin', '0004_alter_facilityreport_facility_and_more'),
        ('HealthcareW', '0003_alter_notification_guardian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='administered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Facilityadmin.healthcarew'),
        ),
    ]
