# Generated by Django 5.2.3 on 2025-07-04 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareW',
            fields=[
                ('worker_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('worker_username', models.CharField(max_length=100, unique=True)),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('position', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse')], max_length=15)),
                ('temporary_password', models.CharField(max_length=120)),
                ('password_changed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], max_length=10)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_left', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Facilityadmin_HealthcareW',
            },
        ),
    ]
