# Generated by Django 5.2.3 on 2025-07-07 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facilityadmin', '0002_initial'),
        ('Sysadmin', '0008_systemactivitylog_systemreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('vaccination_coverage', 'Vaccination Coverage'), ('child_registration', 'Child Registration'), ('growth_monitoring', 'Growth Monitoring'), ('overdue_vaccinations', 'Overdue Vaccinations')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(upload_to='facility_reports/')),
                ('parameters', models.JSONField(default=dict)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sysadmin.healthfacility')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
