# Generated by Django 5.2.3 on 2025-07-07 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facilityadmin', '0003_facilityreport'),
        ('Sysadmin', '0008_systemactivitylog_systemreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityreport',
            name='facility',
            field=models.ForeignKey(db_column='facility_id', on_delete=django.db.models.deletion.CASCADE, to='Sysadmin.healthfacility'),
        ),
        migrations.AlterField(
            model_name='healthcarew',
            name='facility',
            field=models.ForeignKey(db_column='facility_id', on_delete=django.db.models.deletion.CASCADE, to='Sysadmin.healthfacility'),
        ),
    ]
