from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework import status
from django.conf import settings
from django.utils import timezone
from Sysadmin.views.permissions import IsSystemAdmin
from Sysadmin.models.SystemReport import SystemReport
import csv
import os
from django.http import FileResponse

class SystemReportExportView(APIView):
    permission_classes = [IsAuthenticated, IsSystemAdmin]

    def post(self, request):
        report_type = request.data.get('report_type', 'all')
        export_format = request.data.get('format', 'csv')
        now = timezone.now()
        filename = f"system_report_{report_type}_{now.strftime('%Y%m%d%H%M%S')}.{export_format}"
        file_path = os.path.join(settings.MEDIA_ROOT, 'system_reports', filename)
        os.makedirs(os.path.dirname(file_path), exist_ok=True)

        # Example: CSV export
        if export_format == 'csv':
            with open(file_path, 'w', newline='', encoding='utf-8') as csvfile:
                writer = csv.writer(csvfile)
                writer.writerow(['ID', 'Type', 'Generated At', 'Generated By'])
                for report in SystemReport.objects.all():
                    writer.writerow([report.id, report.report_type, report.generated_at, report.generated_by])
        # Example: PDF export (placeholder, implement with ReportLab or similar)
        elif export_format == 'pdf':
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write('PDF export not implemented. Please use CSV.')
        else:
            return Response({'detail': 'Unsupported format.'}, status=status.HTTP_400_BAD_REQUEST)

        # Save SystemReport record
        system_report = SystemReport.objects.create(
            report_type=report_type,
            generated_at=now,
            generated_by=str(request.user),
            report_file=os.path.join('system_reports', filename)
        )
        download_url = request.build_absolute_uri(system_report.report_file.url)
        return Response({'download_url': download_url, 'id': system_report.id}, status=201) 