# Generated by Django 5.2.3 on 2025-07-06 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sysadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='admin',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'FACILITY_ADMIN'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_facility', to=settings.AUTH_USER_MODEL),
        ),
    ]
