# Generated by Django 5.2.3 on 2025-07-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sysadmin', '0002_alter_healthfacility_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthfacility',
            name='id',
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='ID',
            field=models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
