# Generated by Django 5.2.3 on 2025-07-06 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sysadmin', '0003_remove_healthfacility_id_alter_healthfacility_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityadmin',
            name='facility',
            field=models.OneToOneField(db_column='facility_id', on_delete=django.db.models.deletion.CASCADE, to='Sysadmin.healthfacility'),
        ),
    ]
