# Generated by Django 5.2.3 on 2025-07-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sysadmin', '0004_alter_facilityadmin_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityadmin',
            name='ID',
        ),
    ]
