# Generated by Django 5.2.3 on 2025-07-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sysadmin', '0005_remove_facilityadmin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='facility',
        ),
    ]
