# Generated by Django 5.2.3 on 2025-07-06 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sysadmin', '0006_remove_vaccine_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='created_by',
        ),
    ]
