# Generated by Django 5.2.3 on 2025-07-07 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sysadmin', '0007_remove_vaccine_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('facility_created', 'Facility Created'), ('facility_updated', 'Facility Updated'), ('facility_deactivated', 'Facility Deactivated'), ('admin_created', 'Facility Admin Created'), ('admin_updated', 'Facility Admin Updated'), ('vaccine_created', 'Vaccine Created'), ('vaccine_updated', 'Vaccine Updated'), ('report_generated', 'Report Generated')], max_length=30)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('USER_ACTIVITY', 'User Activity Log'), ('LOGIN_HISTORY', 'Login History'), ('PASSWORD_CHANGES', 'Password Changes'), ('ADMIN_ACTIONS', 'Admin Actions'), ('FACILITY_SUMMARY', 'Facility Summary')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(upload_to='system_reports/')),
                ('parameters', models.JSONField(default=dict)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
